### ISSUE TITLE
Assistance with getting started

### ISSUE THREAD

**Issue by bdf0506** [santsleo/AmeritradeAPIonGoogleSheets#1]
Hi,
I really like what you have done here, as I was also trying to use the code by kohjb to get started with this as well. You've added more functions, which is what I am looking for. But, I can't seem to get things started.

It appears that I still need the amtd_SidePane.html from kohjb's code, which isn't in your repo. But then when I put that in, I keep getting:
````
Script function not found: amtd_ShowPane For more information, see https://developers.google.com/apps-script/reference/base/menu#addItem(String,String)
````

Seems like I can somehow force this by manually going into the script, running the amtdShowPane function. But then if I attempt to authenticate, clicking on Step 2 just leads me to nowhere.

If I go back into the script and manually run amtdBackFromPane, then I get the following:

```
TypeError: Cannot read property "returnURI" from undefined.
amtdbackfromPane	@ Ameritrade.gs:168
```

Any pointers? Thank you!

**Comment by santsleo** [comment]
Hi, I'm sorry I'm just seeing this now. 

I see you closed the issue, did you manage to solve it? Because the sheet I created using this code broke because of the api update. So, I thought it would be better to build something in python notebooks (since my usage was only for analysis) using an open-source api wrapper that gets updated frequently to adjust for the api changes. 

I just started working on it and once I finish it I plan to publish it here as well. 

Let me know your updates! Santi
